% Call this to declare constants .

global A_FLL B_FLL HNUM FC FD_SIZE FREQ_STEP FS PLL_LOOP_ORDER TRACK_DIRECTORY
global MAGNITUDE_SMOOTHING LOL_N LOL_M RAW_FILE RECEIVER_FILE
global FSAMP_MSEC  L1 ONE_MSEC_SAM T TP USE_PLL DOPPLER_MAX_PHI_ERR
global W_FC CF_TYPE DB_LIMIT_SMT DB_LIMIT_INS INITIALIZE D1FDT1 D2FDT2
global USE_AIDING  IS_COMPLEX  N_CORR MAX_SPACE CHIPS_PER_CODE CHIP_RATE
global PLL_SWITCH_TIME  COH_INT_TIME COH_INT_SAM C DOPPLER_DB_LIMIT
global CORR_LOSS IF_BANDWIDTH LOL_X BIT_START_TIME_FILE DB_DETECTION 
global POSITION_DB_LIMIT N_CODES_AQU SEARCH_WIN DOPPLER_EXL_RNG POSITION_EXL_RNG
